version: '3'

services:
  arserver:
    image: arcor2/arcor2_arserver_fit_demo:${ARCOR2_VERSION:?ARCOR2_VERSION env variable not set}
    container_name: arserver
    depends_on:
      - project
      - build
      - execution
    ports:
      - "6789:6789"
      - "6780:8888"

    environment:
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:11000            
      - ARCOR2_EXECUTION_URL=ws://execution:6790
      - ARCOR2_BUILDER_URL=http://build:5007
      - ARCOR2_DATA_PATH=/root/data
      - PYTHONPATH=/root/arcor2_fit_demo

  build:
    image: arcor2/arcor2_build:${ARCOR2_BUILD_VERSION:?ARCOR2_BUILD_VERSION env variable not set}
    container_name: build
    environment:
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:11000
      - ARCOR2_DATA_PATH=/root/data
    ports:
      - "5007:5007"
 
  execution:
    image: arcor2/arcor2_execution:${ARCOR2_EXECUTION_VERSION:?ARCOR2_EXECUTION_VERSION env variable not set}
    container_name: execution
    environment:
      - ARCOR2_BUILDER_URL=http://build:5007
      - ARCOR2_DATA_PATH=/root/data
    ports:
      - "5009:5009"

  project:
    image: registry.gitlab.com/kinalisoft/test-it-off/project-web-api:0.2.0
    container_name: "project"
    ports:
      - "11000-11001:11000-11001"
    environment:
      MONGODB_URL: mongodb:27017
    links:
        - mongodb
    depends_on:
        - mongodb

  mongodb:
    image: mongo:4.2.0-bionic
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb-fit-demo:/data/db
    expose:
      - "27017"

volumes:
  mongodb-fit-demo:   



